<?php

declare(strict_types=1);

namespace Tests\Unit\Services;

use Tests\TestCase;
use App\Services\UserService;
use App\Services\EmployeeService;
use App\Repositories\Contracts\UserRepositoryInterface;
use App\Repositories\Contracts\EmployeeRepositoryInterface;
use Mockery;

/**
 * Phase 7 regression tests — mass-assignment protection (P7-8).
 *
 * Repositories build INSERT/UPDATE column lists from array keys, so the
 * services MUST filter client payloads down to an explicit field allowlist.
 * These tests pin the filter: protected/rogue fields must never reach the
 * repository layer, on any of the create/update paths.
 *
 * Protected fields covered here include authentication state
 * (session_token, login_identifier, last_activity), server-owned columns
 * (id, created_at, updated_at, profile_token, profile_image_url), sensitive
 * HR data (salary) and the audited-only status flag (is_active).
 */
class MassAssignmentTest extends TestCase
{
    protected function tearDown(): void
    {
        Mockery::close();
        parent::tearDown();
    }

    /**
     * Fields that must never be client-writable on any user path.
     *
     * @return string[]
     */
    private function forbiddenUserFields(): array
    {
        return [
            'id',
            'session_token',
            'login_identifier',
            'last_activity',
            'profile_token',
            'bogus_column',
        ];
    }

    public function test_user_create_strips_protected_fields(): void
    {
        $repo = Mockery::mock(UserRepositoryInterface::class);
        $repo->shouldReceive('emailExists')->andReturnFalse();

        $captured = null;
        $repo->shouldReceive('create')->once()->andReturnUsing(function (array $data) use (&$captured): int {
            $captured = $data;
            return 1;
        });

        $service = new UserService();
        $service->setUserRepository($repo);

        $payload = [
            'email'            => 'mass.assign@example.test',
            'first_name'       => 'Mass',
            'last_name'        => 'Assignment',
            'role'             => 'officer',
            'password'         => 'Str0ngPassphrase!',
            'phone'            => '0700000000',
            // ---- fields that must be dropped before they reach the repo ----
            'session_token'    => 'forged-session-token',
            'login_identifier' => 'forged-identifier',
            'last_activity'    => '2026-09-01 00:00:00',
            'id'               => 999,
            'created_at'       => '1999-01-01 00:00:00',
            'bogus_column'     => 'unexpected',
            'is_active'        => 0, // create-only: allowed
        ];

        $service->createUser($payload);

        $this->assertIsArray($captured);
        foreach ($this->forbiddenUserFields() as $forbidden) {
            $this->assertArrayNotHasKey($forbidden, $captured, "$forbidden must not be client-writable on create");
        }

        // is_active is explicitly allowed on CREATE, but the service forces
        // the safe default: 0 is coerced to 1 (accounts start active; status
        // changes are the audited toggle-status path).
        $this->assertSame(1, $captured['is_active']);

        // Server-owned timestamps are generated by the service, not the client.
        $this->assertNotSame('1999-01-01 00:00:00', $captured['created_at'] ?? null);

        // The plaintext password never leaves the service unhashed.
        $this->assertStringNotContainsString('Str0ngPassphrase!', (string) ($captured['password'] ?? ''));
    }

    public function test_user_update_strips_protected_fields_including_is_active(): void
    {
        $repo = Mockery::mock(UserRepositoryInterface::class);
        $repo->shouldReceive('findById')->andReturn(['id' => 5, 'role' => 'officer', 'email' => 'old@example.test']);
        $repo->shouldReceive('emailExists')->andReturnFalse();

        $captured = null;
        $roleReached = true;
        $payload = [
            'email'            => 'mass.assign2@example.test',
            'first_name'       => 'Mass',
            'last_name'        => 'Assignment',
            'phone'            => '0711111111',
            'role'             => 'officer',
            // ---- fields that must be dropped before they reach the repo ----
            'is_active'        => 1,   // audited toggle-status endpoint only
            'session_token'    => 'forged-session-token',
            'login_identifier' => 'forged-identifier',
            'bogus_column'     => 'unexpected',
        ];

        $repo->shouldReceive('update')->once()->andReturnUsing(function (int $id, array $data) use (&$captured): bool {
            $captured = $data;
            return true;
        });

        $service = new UserService();
        $service->setUserRepository($repo);

        $service->updateUser(5, $payload);

        $this->assertIsArray($captured);
        foreach ($this->forbiddenUserFields() as $forbidden) {
            $this->assertArrayNotHasKey($forbidden, $captured, "$forbidden must not be client-writable on update");
        }
        // is_active is never client-writable on UPDATE.
        $this->assertArrayNotHasKey('is_active', $captured);
    }

    public function test_employee_create_strips_protected_fields(): void
    {
        $repo = Mockery::mock(EmployeeRepositoryInterface::class);
        $repo->shouldReceive('employeeIdExists')->andReturnFalse();
        $repo->shouldReceive('emailExists')->andReturnFalse();
        $repo->shouldReceive('nationalIdExists')->andReturnFalse();

        $captured = null;
        $repo->shouldReceive('create')->once()->andReturnUsing(function (array $data) use (&$captured): int {
            $captured = $data;
            return 1;
        });

        $service = new EmployeeService();
        $service->setEmployeeRepository($repo);

        $payload = [
            'employee_id'       => 'P7MA001',
            'first_name'        => 'Mass',
            'last_name'         => 'Assignment',
            'national_id'       => '30000001',
            'email'             => 'p7ma001@example.test',
            'employee_type'     => 'officer',
            'employee_status'   => 'active',
            'hire_date'         => '2026-01-01',
            // ---- fields that must be dropped before they reach the repo ----
            'salary'            => 999999.99,
            'profile_token'     => 'forged-profile-token',
            'profile_image_url' => '/forged/path.png',
            'id'                => 999,
            'created_at'        => '1999-01-01 00:00:00',
            'bogus_column'      => 'unexpected',
        ];

        $service->createEmployee($payload);

        $this->assertIsArray($captured);
        foreach (['salary', 'profile_token', 'profile_image_url', 'id', 'bogus_column'] as $forbidden) {
            $this->assertArrayNotHasKey($forbidden, $captured, "$forbidden must not be client-writable on employee create");
        }
        $this->assertNotSame('1999-01-01 00:00:00', $captured['created_at'] ?? null);
    }

    public function test_employee_update_strips_protected_fields(): void
    {
        $repo = Mockery::mock(EmployeeRepositoryInterface::class);
        $repo->shouldReceive('findById')->andReturn(['id' => 7, 'employee_id' => 'P7MA001', 'first_name' => 'Mass']);
        $repo->shouldReceive('employeeIdExists')->andReturnFalse();
        $repo->shouldReceive('emailExists')->andReturnFalse();
        $repo->shouldReceive('nationalIdExists')->andReturnFalse();

        $captured = null;
        $repo->shouldReceive('update')->once()->andReturnUsing(function (int $id, array $data) use (&$captured): bool {
            $captured = $data;
            return true;
        });

        $service = new EmployeeService();
        $service->setEmployeeRepository($repo);

        $payload = [
            'employee_id'     => 'P7MA001',
            'first_name'      => 'Mass',
            'last_name'       => 'Assignment',
            'national_id'     => '30000001',
            'email'           => 'p7ma001@example.test',
            'employee_type'   => 'officer',
            'employee_status' => 'active',
            'hire_date'       => '2026-01-01',
            // ---- fields that must be dropped before they reach the repo ----
            'salary'          => 1.00,
            'profile_token'   => 'forged-profile-token',
            'bogus_column'    => 'unexpected',
        ];

        $service->updateEmployee(7, $payload);

        $this->assertIsArray($captured);
        foreach (['salary', 'profile_token', 'bogus_column'] as $forbidden) {
            $this->assertArrayNotHasKey($forbidden, $captured, "$forbidden must not be client-writable on employee update");
        }
    }

    public function test_employee_profile_update_strips_protected_fields(): void
    {
        $repo = Mockery::mock(EmployeeRepositoryInterface::class);
        $repo->shouldReceive('findById')->andReturn(['id' => 7, 'employee_id' => 'P7MA001', 'first_name' => 'Mass']);

        $captured = null;
        $repo->shouldReceive('update')->once()->andReturnUsing(function (int $id, array $data) use (&$captured): bool {
            $captured = $data;
            return true;
        });

        $service = new EmployeeService();
        $service->setEmployeeRepository($repo);

        // Partial self-service profile update (no full validation path).
        $payload = [
            'phone'         => '0722222222',
            'address'       => '22 Test Street',
            'salary'        => 12345.67,
            'profile_token' => 'forged-profile-token',
            'bogus_column'  => 'unexpected',
        ];

        $service->updateEmployeeProfile(7, $payload);

        $this->assertIsArray($captured);
        foreach (['salary', 'profile_token', 'bogus_column'] as $forbidden) {
            $this->assertArrayNotHasKey($forbidden, $captured, "$forbidden must not be client-writable on profile update");
        }
        $this->assertSame('0722222222', $captured['phone']);
    }
}